<?php

/**
 * This is the model base class for the table "vendor_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VendorType".
 *
 * Columns in table "vendor_type" available as properties of the model,
 * followed by relations of table "vendor_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $program_id
 * @property string $code
 * @property string $create_date
 * @property integer $internal
 * @property string $deleted_at
 *
 * @property Vendor[] $vendors
 * @property Program $program
 */
abstract class BaseVendorType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vendor_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VendorType|VendorTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, program_id, code, internal', 'required'),
			array('program_id, internal', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('code', 'length', 'max'=>10),
			array('deleted_at', 'safe'),
			array('deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, program_id, code, create_date, internal, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'vendors' => array(self::HAS_MANY, 'Vendor', 'type_id'),
			'program' => array(self::BELONGS_TO, 'Program', 'program_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'program_id' => null,
			'code' => Yii::t('app', 'Code'),
			'create_date' => Yii::t('app', 'Create Date'),
			'internal' => Yii::t('app', 'Internal'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'vendors' => null,
			'program' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('program_id', $this->program_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('internal', $this->internal);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}