<?php

/**
 * This is the model base class for the table "distribution".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Distribution".
 *
 * Columns in table "distribution" available as properties of the model,
 * followed by relations of table "distribution" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $start_date
 * @property string $end_date
 * @property integer $region_id
 * @property integer $program_id
 * @property integer $status_id
 * @property string $create_date
 * @property string $deleted_at
 *
 * @property Community $region
 * @property DistributionStatus $status
 * @property Program $program
 * @property DistributionVoucher[] $distributionVouchers
 */
abstract class BaseDistribution extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'distribution';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Distribution|Distributions', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, start_date, region_id, program_id, status_id', 'required'),
			array('region_id, program_id, status_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>10),
			array('end_date, create_date, deleted_at', 'safe'),
			array('end_date, create_date, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, start_date, end_date, region_id, program_id, status_id, create_date, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'region' => array(self::BELONGS_TO, 'Community', 'region_id'),
			'status' => array(self::BELONGS_TO, 'DistributionStatus', 'status_id'),
			'program' => array(self::BELONGS_TO, 'Program', 'program_id'),
			'distributionVouchers' => array(self::HAS_MANY, 'DistributionVoucher', 'distribution_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'region_id' => null,
			'program_id' => null,
			'status_id' => null,
			'create_date' => Yii::t('app', 'Create Date'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'region' => null,
			'status' => null,
			'program' => null,
			'distributionVouchers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('region_id', $this->region_id);
		$criteria->compare('program_id', $this->program_id);
		$criteria->compare('status_id', $this->status_id);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}