<?php

/**
 * This is the model base class for the table "region".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Region".
 *
 * Columns in table "region" available as properties of the model,
 * followed by relations of table "region" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $create_date
 * @property string $deleted_at
 * @property integer $city_id
 *
 * @property Distribution[] $distributions
 * @property City $city
 */
abstract class BaseRegion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'region';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Region|Regions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, city_id', 'required'),
			array('city_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('deleted_at', 'safe'),
			array('deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, create_date, deleted_at, city_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'distributions' => array(self::HAS_MANY, 'Distribution', 'region_id'),
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'create_date' => Yii::t('app', 'Create Date'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'city_id' => null,
			'distributions' => null,
			'city' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);
		$criteria->compare('city_id', $this->city_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}