<?php

/**
 * This is the model base class for the table "beneficiary_attribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeneficiaryAttribute".
 *
 * Columns in table "beneficiary_attribute" available as properties of the model,
 * followed by relations of table "beneficiary_attribute" available as properties of the model.
 *
 * @property integer $id
 * @property integer $beneficiary_id
 * @property integer $attribute_id
 * @property string $value
 * @property string $create_date
 * @property string $code
 * @property string $deleted_at
 *
 * @property Attribute $attribute
 * @property Beneficiary $beneficiary
 */
abstract class BaseBeneficiaryAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beneficiary_attribute';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeneficiaryAttribute|BeneficiaryAttributes', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('beneficiary_id, attribute_id', 'required'),
			array('beneficiary_id, attribute_id', 'numerical', 'integerOnly'=>true),
			array('value', 'length', 'max'=>255),
			array('deleted_at', 'safe'),
			array('value, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, beneficiary_id, attribute_id, value, create_date, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attribute' => array(self::BELONGS_TO, 'Attribute', 'attribute_id'),
			'beneficiary' => array(self::BELONGS_TO, 'Beneficiary', 'beneficiary_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'beneficiary_id' => null,
			'attribute_id' => null,
			'value' => Yii::t('app', 'Value'),
			'create_date' => Yii::t('app', 'Create Date'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attribute' => null,
			'beneficiary' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('beneficiary_id', $this->beneficiary_id);
		$criteria->compare('attribute_id', $this->attribute_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}