<?php

/**
 * This is the model base class for the table "governorate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Governorate".
 *
 * Columns in table "governorate" available as properties of the model,
 * followed by relations of table "governorate" available as properties of the model.
 *
 * @property integer $id
 * @property string $en_name
 * @property string $code
 * @property string $ar_name
 * @property integer $country_id
 *
 * @property District[] $districts
 * @property Country $country
 */
abstract class BaseGovernorate extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'governorate';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Governorate|Governorates', $n);
	}

	public static function representingColumn() {
		return 'en_name';
	}

	public function rules() {
		return array(
			array('en_name, code, ar_name, country_id', 'required'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('en_name, ar_name', 'length', 'max'=>255),
			array('code', 'length', 'max'=>10),
			array('id, en_name, code, ar_name, country_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'districts' => array(self::HAS_MANY, 'District', 'governerate_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'en_name' => Yii::t('app', 'En Name'),
			'code' => Yii::t('app', 'Code'),
			'ar_name' => Yii::t('app', 'Ar Name'),
			'country_id' => null,
			'districts' => null,
			'country' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('en_name', $this->en_name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('ar_name', $this->ar_name, true);
		$criteria->compare('country_id', $this->country_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}