<?php

/**
 * This is the model base class for the table "province".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Province".
 *
 * Columns in table "province" available as properties of the model,
 * followed by relations of table "province" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $create_date
 * @property string $deleted_at
 * @property integer $country_id
 *
 * @property City[] $cities
 * @property Country $country
 */
abstract class BaseProvince extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'province';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Province|Provinces', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, country_id', 'required'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('deleted_at', 'safe'),
			array('deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, create_date, deleted_at, country_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'City', 'province_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'create_date' => Yii::t('app', 'Create Date'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'country_id' => null,
			'cities' => null,
			'country' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);
		$criteria->compare('country_id', $this->country_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}