<?php

/**
 * This is the model base class for the table "vendor_note".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VendorNote".
 *
 * Columns in table "vendor_note" available as properties of the model,
 * followed by relations of table "vendor_note" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property string $text
 * @property string $create_date
 * @property string $deleted_at
 *
 * @property Vendor $vendor
 */
abstract class BaseVendorNote extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vendor_note';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VendorNote|VendorNotes', $n);
	}

	public static function representingColumn() {
		return 'text';
	}

	public function rules() {
		return array(
			array('vendor_id, text, create_date', 'required'),
			array('vendor_id', 'numerical', 'integerOnly'=>true),
			array('deleted_at', 'safe'),
			array('deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vendor_id, text, create_date, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vendor_id' => null,
			'text' => Yii::t('app', 'Text'),
			'create_date' => Yii::t('app', 'Create Date'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'vendor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}