<?php

/**
 * This is the model base class for the table "attribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Attribute".
 *
 * Columns in table "attribute" available as properties of the model,
 * followed by relations of table "attribute" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $create_date
 * @property integer $valid
 * @property string $security_level
 * @property integer $family
 * @property string $deleted_at
 *
 * @property BeneficiaryAttribute[] $beneficiaryAttributes
 */
abstract class BaseAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attribute';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Attribute|Attributes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, family', 'required'),
			array('valid, family', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('security_level', 'length', 'max'=>5),
			array('description, deleted_at', 'safe'),
			array('description, valid, security_level, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, create_date, valid, security_level, family, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'beneficiaryAttributes' => array(self::HAS_MANY, 'BeneficiaryAttribute', 'attribute_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'create_date' => Yii::t('app', 'Create Date'),
			'valid' => Yii::t('app', 'Valid'),
			'security_level' => Yii::t('app', 'Security Level'),
			'family' => Yii::t('app', 'Family'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'beneficiaryAttributes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('valid', $this->valid);
		$criteria->compare('security_level', $this->security_level, true);
		$criteria->compare('family', $this->family);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}